#!/usr/bin/env python3
"""Generate data/moves/moves.json and the move section of data/localization/ja.json.
Compact DSL: (id, ja, type, category, power, accuracy, pp, priority, target, flags, extra)
flags tokens: c=contact p=protect m=mirror s=sound sl=slicing pu=punch bi=bite bu=bullet pw=powder
              w=wind h=heal r=recharge d=defrost bs=bypasssub rf=reflectable cm=crushes_minimized
              ch=charge da=dance pl=pulse
targets: N=normal S=self F=allAdjacentFoes A=allAdjacent AL=adjacentAlly AS=allySide FS=foeSide
         ALL=all AT=allyTeam RN=randomNormal SC=scripted
"""
import json, os
FLAG = {"c":"contact","p":"protect","m":"mirror","s":"sound","sl":"slicing","pu":"punch","bi":"bite","bu":"bullet",
        "pw":"powder","w":"wind","h":"heal","r":"recharge","d":"defrost","bs":"bypasssub","rf":"reflectable",
        "cm":"crushes_minimized","ch":"charge","da":"dance","pl":"pulse"}
TGT = {"N":"normal","S":"self","F":"allAdjacentFoes","A":"allAdjacent","AL":"adjacentAlly","AS":"allySide",
       "FS":"foeSide","ALL":"all","AT":"allyTeam","RN":"randomNormal","SC":"scripted"}
T = True
def sec(chance, **kw): return {"secondary": dict(chance=chance, **kw)}
def selfb(**b): return {"self": {"boosts": b}}
def boosts(**b): return {"boosts": b}

M = []
def mv(id, ja, type, cat, power, acc, pp, prio, tgt, flags, **extra):
    M.append((id, ja, type, cat, power, acc, pp, prio, tgt, flags, extra))

# ---------------- NORMAL ----------------
mv("tackle","たいあたり","normal","physical",40,100,35,0,"N","c p m")
mv("scratch","ひっかく","normal","physical",40,100,35,0,"N","c p m")
mv("pound","はたく","normal","physical",40,100,35,0,"N","c p m")
mv("focus_energy","きあいだめ","normal","status",0,T,30,0,"S","",volatile_status="focus_energy")
mv("quick_attack","でんこうせっか","normal","physical",40,100,30,1,"N","c p m")
mv("extreme_speed","しんそく","normal","physical",80,100,5,2,"N","c p m")
mv("body_slam","のしかかり","normal","physical",85,100,15,0,"N","c p m cm",**sec(30,status="par"))
mv("double_edge","すてみタックル","normal","physical",120,100,15,0,"N","c p m",recoil=[33,100])
mv("take_down","とっしん","normal","physical",90,85,20,0,"N","c p m",recoil=[1,4])
mv("facade","からげんき","normal","physical",70,100,20,0,"N","c p m",base_power_callback="facade",ignore_burn=True)
mv("hyper_voice","ハイパーボイス","normal","special",90,100,10,0,"F","p m s bs")
mv("boomburst","ばくおんぱ","normal","special",140,100,10,0,"A","p m s bs")
mv("hyper_beam","はかいこうせん","normal","special",150,90,5,0,"N","p m r")
mv("giga_impact","ギガインパクト","normal","physical",150,90,5,0,"N","c p m r")
mv("tri_attack","トライアタック","normal","special",80,100,10,0,"N","p m",effect="tri_attack")
mv("stomp","ふみつけ","normal","physical",65,100,20,0,"N","c p m cm",**sec(30,volatile_status="flinch"))
mv("headbutt","ずつき","normal","physical",70,100,15,0,"N","c p m",**sec(30,volatile_status="flinch"))
mv("mega_kick","メガトンキック","normal","physical",120,75,5,0,"N","c p m")
mv("slash","きりさく","normal","physical",70,100,20,0,"N","c p m sl",crit_ratio=2)
mv("cut","いあいぎり","normal","physical",50,95,30,0,"N","c p m sl")
mv("false_swipe","みねうち","normal","physical",40,100,40,0,"N","c p m",leaves_1hp=True)
mv("endeavor","がむしゃら","normal","physical",0,100,5,0,"N","c p m",damage_callback="endeavor")
mv("super_fang","いかりのまえば","normal","physical",0,90,10,0,"N","c p m",damage_callback="half_hp")
mv("swift","スピードスター","normal","special",60,T,20,0,"F","p m")
mv("protect","まもる","normal","status",0,T,10,4,"S","",volatile_status="protect",effect="protect",stalling=True)
mv("endure","こらえる","normal","status",0,T,10,4,"S","",volatile_status="endure",effect="protect",stalling=True)
mv("substitute","みがわり","normal","status",0,T,10,0,"S","",volatile_status="substitute",effect="substitute")
mv("rest","ねむる","psychic","status",0,T,5,0,"S","h",effect="rest",sleep_turns=3)
mv("sleep_talk","ねごと","normal","status",0,T,10,0,"S","",effect="sleep_talk",sleep_usable=True,no_sleep_talk=True,no_encore=True)
mv("snore","いびき","normal","special",50,100,15,0,"N","p m s bs",sleep_usable=True,effect="snore",**sec(30,volatile_status="flinch"))
mv("swords_dance","つるぎのまい","normal","status",0,T,20,0,"S","da",**boosts(atk=2))
mv("growl","なきごえ","normal","status",0,100,40,0,"F","p m s rf bs",**boosts(atk=-1))
mv("leer","にらみつける","normal","status",0,100,30,0,"F","p m rf",**boosts(**{"def":-1}))
mv("tail_whip","しっぽをふる","normal","status",0,100,30,0,"F","p m rf",**boosts(**{"def":-1}))
mv("screech","いやなおと","normal","status",0,85,40,0,"N","p m s rf bs",**boosts(**{"def":-2}))
mv("scary_face","こわいかお","normal","status",0,100,10,0,"N","p m rf",**boosts(spe=-2))
mv("minimize","ちいさくなる","normal","status",0,T,10,0,"S","",volatile_status="minimize",**boosts(evasion=2))
mv("double_team","かげぶんしん","normal","status",0,T,15,0,"S","",**boosts(evasion=1))
mv("harden","かたくなる","normal","status",0,T,30,0,"S","",**boosts(**{"def":1}))
mv("work_up","ふるいたてる","normal","status",0,T,30,0,"S","",**boosts(atk=1,spa=1))
mv("howl","とおぼえ","normal","status",0,T,40,0,"S","s",**boosts(atk=1))
mv("belly_drum","はらだいこ","normal","status",0,T,10,0,"S","",effect="belly_drum")
mv("encore","アンコール","normal","status",0,100,5,0,"N","p m rf bs",volatile_status="encore",no_encore=True)
mv("disable","かなしばり","normal","status",0,100,20,0,"N","p m rf bs",volatile_status="disable")
mv("attract","メロメロ","normal","status",0,100,15,0,"N","p m rf",volatile_status="attract")
mv("yawn","あくび","normal","status",0,T,10,0,"N","p m rf",volatile_status="yawn",effect="yawn")
mv("wish","ねがいごと","normal","status",0,T,10,0,"S","h",effect="wish")
mv("heal_bell","いやしのすず","normal","status",0,T,5,0,"AT","s bs",effect="heal_bell")
mv("soft_boiled","タマゴうみ","normal","status",0,T,5,0,"S","h",heal=[1,2])
mv("recover","じこさいせい","normal","status",0,T,5,0,"S","h",heal=[1,2])
mv("slack_off","なまける","normal","status",0,T,5,0,"S","h",heal=[1,2])
mv("milk_drink","ミルクのみ","normal","status",0,T,5,0,"S","h",heal=[1,2])
mv("morning_sun","あさのひざし","normal","status",0,T,5,0,"S","h",effect="weather_heal")
mv("safeguard","しんぴのまもり","normal","status",0,T,25,0,"AS","",side_condition="safeguard")
mv("whirlwind","ふきとばし","normal","status",0,T,20,-6,"N","p m rf bs w",force_switch=True)
mv("roar","ほえる","normal","status",0,T,20,-6,"N","p m s rf bs",force_switch=True)
mv("baton_pass","バトンタッチ","normal","status",0,T,40,0,"S","",self_switch="copyvolatile",effect="baton_pass")
mv("helping_hand","てだすけ","normal","status",0,T,20,5,"AL","bs",volatile_status="helping_hand",no_sleep_talk=True)
mv("follow_me","このゆびとまれ","normal","status",0,T,20,2,"S","",volatile_status="follow_me")
mv("tearful_look","なみだめ","normal","status",0,T,20,0,"N","p rf m",**boosts(atk=-1,spa=-1))
mv("noble_roar","おたけび","normal","status",0,100,30,0,"N","p m s rf bs",**boosts(atk=-1,spa=-1))
mv("play_nice","なかよくする","normal","status",0,T,20,0,"N","m rf bs",**boosts(atk=-1))
mv("pain_split","いたみわけ","normal","status",0,T,20,0,"N","p m",effect="pain_split")
mv("fake_out","ねこだまし","normal","physical",40,100,10,3,"N","c p m",effect="fake_out",**sec(100,volatile_status="flinch"))
mv("rapid_spin","こうそくスピン","normal","physical",50,100,40,0,"N","c p m",effect="rapid_spin",**selfb(spe=1))
mv("explosion","だいばくはつ","normal","physical",250,100,5,0,"A","p m",self_destruct="always")
mv("self_destruct","じばく","normal","physical",200,100,5,0,"A","p m",self_destruct="always")
mv("crush_claw","ブレイククロー","normal","physical",75,95,10,0,"N","c p m",**sec(50,boosts={"def":-1}))
mv("retaliate","かたきうち","normal","physical",70,100,5,0,"N","c p m")
mv("double_hit","ダブルアタック","normal","physical",35,90,10,0,"N","c p m",multihit=2)
mv("fury_swipes","みだれひっかき","normal","physical",18,80,15,0,"N","c p m",multihit=[2,5])
mv("strength","かいりき","normal","physical",80,100,15,0,"N","c p m")
mv("hyper_fang","ひっさつまえば","normal","physical",80,90,15,0,"N","c p m bi",**sec(10,volatile_status="flinch"))
mv("mega_punch","メガトンパンチ","normal","physical",80,85,20,0,"N","c p m pu")
mv("lovely_kiss","あくまのキッス","normal","status",0,75,10,0,"N","p m rf",status="slp")
mv("sing","うたう","normal","status",0,55,15,0,"N","p m s rf bs",status="slp")
mv("supersonic","ちょうおんぱ","normal","status",0,55,20,0,"N","p m s rf bs",volatile_status="confusion")
mv("swagger","いばる","normal","status",0,85,15,0,"N","p m rf",volatile_status="confusion",**boosts(atk=2))
mv("psych_up","じこあんじ","normal","status",0,T,10,0,"N","bs",effect="psych_up")
mv("weather_ball","ウェザーボール","normal","special",50,100,10,0,"N","p m bu",effect="weather_ball",no_type_change=True)
mv("laser_focus","とぎすます","normal","status",0,T,30,0,"S","",volatile_status="laser_focus")
mv("block","とおせんぼう","normal","status",0,T,5,0,"N","m rf",volatile_status="trapped",effect="trap_move")
mv("mean_look","くろいまなざし","normal","status",0,T,5,0,"N","m rf",volatile_status="trapped",effect="trap_move")
mv("bind","しめつける","normal","physical",15,85,20,0,"N","c p m",volatile_status="partially_trapped")
mv("wrap","まきつく","normal","physical",15,90,20,0,"N","c p m",volatile_status="partially_trapped")
mv("population_bomb","ネズミざん","normal","physical",20,90,10,0,"N","c p m sl",multihit=10,multi_accuracy=True)
mv("shell_smash","からをやぶる","normal","status",0,T,15,0,"S","",**boosts(atk=2,spa=2,spe=2,**{"def":-1,"spd":-1}))
mv("struggle","わるあがき","???","physical",50,T,1,0,"RN","c",effect="struggle",no_pp_boosts=True,no_sleep_talk=True,no_encore=True,ignore_immunity=True)
mv("tickle","くすぐる","normal","status",0,100,20,0,"N","p m rf",**boosts(atk=-1,**{"def":-1}))
mv("thrash","あばれる","normal","physical",120,100,10,0,"RN","c p m",locked_move=True)
mv("glare","へびにらみ","normal","status",0,100,30,0,"N","p m rf",status="par")
mv("flail","じたばた","normal","physical",0,100,15,0,"N","c p m",base_power_callback="low_hp")
mv("crush_grip","にぎりつぶす","normal","physical",0,100,5,0,"N","c p m",base_power_callback="target_hp")
mv("chip_away","なしくずし","normal","physical",70,100,20,0,"N","c p m",ignore_defensive=True,ignore_evasion=True)
mv("acupressure","つぼをつく","normal","status",0,T,30,0,"S","",effect="acupressure")
mv("sand_attack","すなかけ","ground","status",0,100,15,0,"N","p m rf",**boosts(accuracy=-1))
# ---------------- FIRE ----------------
mv("ember","ひのこ","fire","special",40,100,25,0,"N","p m",**sec(10,status="brn"))
mv("flamethrower","かえんほうしゃ","fire","special",90,100,15,0,"N","p m",**sec(10,status="brn"))
mv("fire_blast","だいもんじ","fire","special",110,85,5,0,"N","p m",**sec(10,status="brn"))
mv("overheat","オーバーヒート","fire","special",130,90,5,0,"N","p m",**selfb(spa=-2))
mv("heat_wave","ねっぷう","fire","special",95,90,10,0,"F","p m w",**sec(10,status="brn"))
mv("flame_charge","ニトロチャージ","fire","physical",50,100,20,0,"N","c p m",**selfb(spe=1))
mv("fire_punch","ほのおのパンチ","fire","physical",75,100,15,0,"N","c p m pu",**sec(10,status="brn"))
mv("flare_blitz","フレアドライブ","fire","physical",120,100,15,0,"N","c p m d",recoil=[33,100],**sec(10,status="brn"))
mv("fire_fang","ほのおのキバ","fire","physical",65,95,15,0,"N","c p m bi",secondaries=[{"chance":10,"status":"brn"},{"chance":10,"volatile_status":"flinch"}])
mv("flame_wheel","かえんぐるま","fire","physical",60,100,25,0,"N","c p m d",**sec(10,status="brn"))
mv("will_o_wisp","おにび","fire","status",0,85,15,0,"N","p m rf",status="brn")
mv("sunny_day","にほんばれ","fire","status",0,T,5,0,"ALL","",weather="sun")
mv("lava_plume","ふんえん","fire","special",80,100,15,0,"A","p m",**sec(30,status="brn"))
mv("fire_lash","ほのおのムチ","fire","physical",80,100,15,0,"N","c p m",**sec(100,boosts={"def":-1}))
mv("bitter_blade","むねんのつるぎ","fire","physical",90,100,10,0,"N","c p m sl h",drain=[1,2])
mv("mystical_fire","マジカルフレイム","fire","special",75,100,10,0,"N","p m",**sec(100,boosts={"spa":-1}))
mv("fire_spin","ほのおのうず","fire","special",35,85,15,0,"N","p m",volatile_status="partially_trapped")
mv("blaze_kick","ブレイズキック","fire","physical",85,90,10,0,"N","c p m",crit_ratio=2,**sec(10,status="brn"))
mv("eruption","ふんか","fire","special",150,100,5,0,"F","p m",base_power_callback="user_hp")
mv("heat_crash","ヒートスタンプ","fire","physical",0,100,10,0,"N","c p m cm",base_power_callback="heavy_slam")
mv("fiery_dance","ほのおのまい","fire","special",80,100,10,0,"N","p m da",**sec(50,self={"boosts":{"spa":1}}))
mv("torch_song","フレアソング","fire","special",80,100,10,0,"N","p m s bs",**sec(100,self={"boosts":{"spa":1}}))
mv("armor_cannon","アーマーキャノン","fire","special",120,100,5,0,"N","p m",**selfb(**{"def":-1,"spd":-1}))
mv("inferno","れんごく","fire","special",100,50,5,0,"N","p m",**sec(100,status="brn"))
mv("scorching_sands","ねっさのだいち","ground","special",70,100,10,0,"N","p m d",thaws_target=True,**sec(30,status="brn"))
# ---------------- WATER ----------------
mv("water_gun","みずでっぽう","water","special",40,100,25,0,"N","p m")
mv("hydro_pump","ハイドロポンプ","water","special",110,80,5,0,"N","p m")
mv("surf","なみのり","water","special",90,100,15,0,"A","p m")
mv("scald","ねっとう","water","special",80,100,15,0,"N","p m d",thaws_target=True,**sec(30,status="brn"))
mv("waterfall","たきのぼり","water","physical",80,100,15,0,"N","c p m",**sec(20,volatile_status="flinch"))
mv("liquidation","アクアブレイク","water","physical",85,100,10,0,"N","c p m",**sec(20,boosts={"def":-1}))
mv("aqua_jet","アクアジェット","water","physical",40,100,20,1,"N","c p m")
mv("aqua_tail","アクアテール","water","physical",90,90,10,0,"N","c p m")
mv("flip_turn","クイックターン","water","physical",60,100,20,0,"N","c p m",self_switch=True)
mv("wave_crash","ウェーブタックル","water","physical",120,100,10,0,"N","c p m",recoil=[33,100])
mv("aqua_cutter","アクアカッター","water","physical",70,95,20,0,"N","p m sl",crit_ratio=2)
mv("razor_shell","シェルブレード","water","physical",75,95,10,0,"N","c p m sl",**sec(50,boosts={"def":-1}))
mv("water_pulse","みずのはどう","water","special",60,100,20,0,"N","p m pl",**sec(20,volatile_status="confusion"))
mv("whirlpool","うずしお","water","special",35,85,15,0,"N","p m",volatile_status="partially_trapped")
mv("muddy_water","だくりゅう","water","special",90,85,10,0,"F","p m",**sec(30,boosts={"accuracy":-1}))
mv("brine","しおみず","water","special",65,100,10,0,"N","p m",base_power_callback="brine")
mv("water_spout","しおふき","water","special",150,100,5,0,"F","p m",base_power_callback="user_hp")
mv("aqua_ring","アクアリング","water","status",0,T,20,0,"S","",volatile_status="aqua_ring")
mv("rain_dance","あまごい","water","status",0,T,5,0,"ALL","",weather="rain")
mv("chilling_water","つめたいみず","water","special",50,100,20,0,"N","p m",**sec(100,boosts={"atk":-1}))
mv("crabhammer","クラブハンマー","water","physical",100,90,10,0,"N","c p m",crit_ratio=2)
mv("bubble_beam","バブルこうせん","water","special",65,100,20,0,"N","p m",**sec(10,boosts={"spe":-1}))
mv("water_shuriken","みずしゅりけん","water","special",15,100,20,1,"N","p m",multihit=[2,5])
mv("soak","みずびたし","water","status",0,100,20,0,"N","p m rf",effect="soak")
mv("jet_punch","ジェットパンチ","water","physical",60,100,15,1,"N","c p m pu")
mv("clamp","からではさむ","water","physical",35,85,15,0,"N","c p m",volatile_status="partially_trapped")
mv("sparkling_aria","うたかたのアリア","water","special",90,100,10,0,"A","p m s bs")
# ---------------- ELECTRIC ----------------
mv("thunder_shock","でんきショック","electric","special",40,100,30,0,"N","p m",**sec(10,status="par"))
mv("thunderbolt","10まんボルト","electric","special",90,100,15,0,"N","p m",**sec(10,status="par"))
mv("thunder","かみなり","electric","special",110,70,10,0,"N","p m",always_hit_in=["rain"],accuracy_in={"sun":50},hits_invulnerable=["fly"],**sec(30,status="par"))
mv("volt_switch","ボルトチェンジ","electric","special",70,100,20,0,"N","p m",self_switch=True)
mv("discharge","ほうでん","electric","special",80,100,15,0,"A","p m",**sec(30,status="par"))
mv("thunder_wave","でんじは","electric","status",0,90,20,0,"N","p m rf",status="par",ignore_immunity=False)
mv("wild_charge","ワイルドボルト","electric","physical",90,100,15,0,"N","c p m",recoil=[1,4])
mv("zing_zap","びりびりちくちく","electric","physical",80,100,10,0,"N","c p m",**sec(30,volatile_status="flinch"))
mv("thunder_punch","かみなりパンチ","electric","physical",75,100,15,0,"N","c p m pu",**sec(10,status="par"))
mv("spark","スパーク","electric","physical",65,100,20,0,"N","c p m",**sec(30,status="par"))
mv("nuzzle","ほっぺすりすり","electric","physical",20,100,20,0,"N","c p m",**sec(100,status="par"))
mv("electro_ball","エレキボール","electric","special",0,100,10,0,"N","p m bu",base_power_callback="speed_ratio")
mv("charge_beam","チャージビーム","electric","special",50,90,10,0,"N","p m",**sec(70,self={"boosts":{"spa":1}}))
mv("volt_tackle","ボルテッカー","electric","physical",120,100,15,0,"N","c p m",recoil=[33,100],**sec(10,status="par"))
mv("thunder_fang","かみなりのキバ","electric","physical",65,95,15,0,"N","c p m bi",secondaries=[{"chance":10,"status":"par"},{"chance":10,"volatile_status":"flinch"}])
mv("electric_terrain","エレキフィールド","electric","status",0,T,10,0,"ALL","",terrain="electric")
mv("electroweb","エレキネット","electric","special",55,95,15,0,"F","p m",**sec(100,boosts={"spe":-1}))
mv("charge","じゅうでん","electric","status",0,T,20,0,"S","",volatile_status="charge",**boosts(spd=1))
mv("parabolic_charge","パラボラチャージ","electric","special",65,100,20,0,"A","p m h",drain=[1,2])
mv("zap_cannon","でんじほう","electric","special",120,50,5,0,"N","p m bu",**sec(100,status="par"))
mv("magnet_rise","でんじふゆう","electric","status",0,T,10,0,"S","",volatile_status="magnet_rise")
mv("eerie_impulse","かいでんぱ","electric","status",0,100,15,0,"N","p m rf",**boosts(spa=-2))
mv("overdrive","オーバードライブ","electric","special",80,100,10,0,"F","p m s bs")
mv("supercell_slam","サンダーダイブ","electric","physical",100,95,15,0,"N","c p m",effect="high_jump_kick")
# ---------------- GRASS ----------------
mv("absorb","すいとる","grass","special",20,100,25,0,"N","p m h",drain=[1,2])
mv("mega_drain","メガドレイン","grass","special",40,100,15,0,"N","p m h",drain=[1,2])
mv("giga_drain","ギガドレイン","grass","special",75,100,10,0,"N","p m h",drain=[1,2])
mv("leaf_storm","リーフストーム","grass","special",130,90,5,0,"N","p m",**selfb(spa=-2))
mv("energy_ball","エナジーボール","grass","special",90,100,10,0,"N","p m bu",**sec(10,boosts={"spd":-1}))
mv("leaf_blade","リーフブレード","grass","physical",90,100,15,0,"N","c p m sl",crit_ratio=2)
mv("solar_beam","ソーラービーム","grass","special",120,100,10,0,"N","p m ch",effect="charge_move",charge_skip_weather="sun",no_sleep_talk=True)
mv("solar_blade","ソーラーブレード","grass","physical",125,100,10,0,"N","c p m sl ch",effect="charge_move",charge_skip_weather="sun",no_sleep_talk=True)
mv("grassy_terrain","グラスフィールド","grass","status",0,T,10,0,"ALL","",terrain="grassy")
mv("spore","キノコのほうし","grass","status",0,100,15,0,"N","p m pw rf",status="slp")
mv("sleep_powder","ねむりごな","grass","status",0,75,15,0,"N","p m pw rf",status="slp")
mv("stun_spore","しびれごな","grass","status",0,75,30,0,"N","p m pw rf",status="par")
mv("poison_powder","どくのこな","poison","status",0,75,35,0,"N","p m pw rf",status="psn")
mv("leech_seed","やどりぎのタネ","grass","status",0,90,10,0,"N","p m rf",volatile_status="leech_seed")
mv("synthesis","こうごうせい","grass","status",0,T,5,0,"S","h",effect="weather_heal")
mv("grass_knot","くさむすび","grass","special",0,100,20,0,"N","c p m",base_power_callback="weight")
mv("power_whip","パワーウィップ","grass","physical",120,85,10,0,"N","c p m")
mv("wood_hammer","ウッドハンマー","grass","physical",120,100,15,0,"N","c p m",recoil=[33,100])
mv("seed_bomb","タネばくだん","grass","physical",80,100,15,0,"N","p m bu")
mv("horn_leech","ウッドホーン","grass","physical",75,100,10,0,"N","c p m h",drain=[1,2])
mv("petal_dance","はなびらのまい","grass","special",120,100,10,0,"RN","c p m da",locked_move=True)
mv("petal_blizzard","はなふぶき","grass","physical",90,100,15,0,"A","p m w")
mv("razor_leaf","はっぱカッター","grass","physical",55,95,25,0,"F","p m sl",crit_ratio=2)
mv("magical_leaf","マジカルリーフ","grass","special",60,T,20,0,"N","p m")
mv("strength_sap","ちからをすいとる","grass","status",0,100,10,0,"N","p m rf h",effect="strength_sap")
mv("grassy_glide","グラススライダー","grass","physical",55,100,20,0,"N","c p m",effect="grassy_glide")
mv("bullet_seed","タネマシンガン","grass","physical",25,100,30,0,"N","p m bu",multihit=[2,5])
mv("cotton_spore","わたほうし","grass","status",0,100,40,0,"F","p m pw rf",**boosts(spe=-2))
mv("trop_kick","トロピカルキック","grass","physical",70,100,15,0,"N","c p m",**sec(100,boosts={"atk":-1}))
mv("apple_acid","リンゴさん","grass","special",80,100,10,0,"N","p m",**sec(100,boosts={"spd":-1}))
mv("grav_apple","Gのちから","grass","physical",80,100,10,0,"N","p m",**sec(100,boosts={"def":-1}))
mv("leafage","このは","grass","physical",40,100,40,0,"N","p m")
mv("vine_whip","つるのムチ","grass","physical",45,100,25,0,"N","c p m")
mv("growth","せいちょう","normal","status",0,T,20,0,"S","",effect="growth",**boosts(atk=1,spa=1))
mv("aromatherapy","アロマセラピー","grass","status",0,T,5,0,"AT","",effect="heal_bell")
mv("drum_beating","ドラムアタック","grass","physical",80,100,10,0,"N","p m",**sec(100,boosts={"spe":-1}))
mv("spiky_shield","ニードルガード","grass","status",0,T,10,4,"S","",volatile_status="spiky_shield",effect="protect",stalling=True)
mv("cotton_guard","コットンガード","grass","status",0,T,10,0,"S","",**boosts(**{"def":3}))
mv("ingrain","ねをはる","grass","status",0,T,20,0,"S","",volatile_status="ingrain")
mv("leaf_tornado","グラスミキサー","grass","special",65,90,10,0,"N","p m",**sec(50,boosts={"accuracy":-1}))
mv("trailblaze","くさわけ","grass","physical",50,100,20,0,"N","c p m",**selfb(spe=1))
# ---------------- ICE ----------------
mv("ice_beam","れいとうビーム","ice","special",90,100,10,0,"N","p m",**sec(10,status="frz"))
mv("blizzard","ふぶき","ice","special",110,70,5,0,"F","p m w",always_hit_in=["snow"],**sec(10,status="frz"))
mv("freeze_dry","フリーズドライ","ice","special",70,100,20,0,"N","p m",effect="freeze_dry",**sec(10,status="frz"))
mv("icicle_crash","つららおとし","ice","physical",85,90,10,0,"N","p m",**sec(30,volatile_status="flinch"))
mv("ice_shard","こおりのつぶて","ice","physical",40,100,30,1,"N","p m")
mv("icicle_spear","つららばり","ice","physical",25,100,30,0,"N","p m",multihit=[2,5])
mv("ice_punch","れいとうパンチ","ice","physical",75,100,15,0,"N","c p m pu",**sec(10,status="frz"))
mv("ice_fang","こおりのキバ","ice","physical",65,95,15,0,"N","c p m bi",secondaries=[{"chance":10,"status":"frz"},{"chance":10,"volatile_status":"flinch"}])
mv("frost_breath","こおりのいぶき","ice","special",60,90,10,0,"N","p m",will_crit=True)
mv("aurora_veil","オーロラベール","ice","status",0,T,20,0,"AS","",side_condition="aurora_veil",effect="aurora_veil")
mv("snowscape","ゆきげしき","ice","status",0,T,10,0,"ALL","",weather="snow")
mv("icy_wind","こごえるかぜ","ice","special",55,95,15,0,"F","p m w",**sec(100,boosts={"spe":-1}))
mv("avalanche","ゆきなだれ","ice","physical",60,100,10,-4,"N","c p m",base_power_callback="avalanche")
mv("aurora_beam","オーロラビーム","ice","special",65,100,20,0,"N","p m",**sec(10,boosts={"atk":-1}))
mv("ice_spinner","アイススピナー","ice","physical",80,100,15,0,"N","c p m",effect="ice_spinner")
mv("haze","くろいきり","ice","status",0,T,30,0,"ALL","",effect="haze")
mv("mist","しろいきり","ice","status",0,T,30,0,"AS","",side_condition="mist")
mv("powder_snow","こなゆき","ice","special",40,100,25,0,"F","p m",**sec(10,status="frz"))
mv("ice_hammer","アイスハンマー","ice","physical",100,90,10,0,"N","c p m pu",**selfb(spe=-1))
# ---------------- FIGHTING ----------------
mv("close_combat","インファイト","fighting","physical",120,100,5,0,"N","c p m",**selfb(**{"def":-1,"spd":-1}))
mv("sacred_sword","せいなるつるぎ","fighting","physical",90,100,15,0,"N","c p m sl",ignore_defensive=True,ignore_evasion=True)
mv("drain_punch","ドレインパンチ","fighting","physical",75,100,10,0,"N","c p m pu h",drain=[1,2])
mv("mach_punch","マッハパンチ","fighting","physical",40,100,30,1,"N","c p m pu")
mv("aura_sphere","はどうだん","fighting","special",80,T,20,0,"N","p m bu pl")
mv("focus_blast","きあいだま","fighting","special",120,70,5,0,"N","p m bu",**sec(10,boosts={"spd":-1}))
mv("superpower","ばかぢから","fighting","physical",120,100,5,0,"N","c p m",**selfb(atk=-1,**{"def":-1}))
mv("body_press","ボディプレス","fighting","physical",80,100,10,0,"N","c p m",override_offensive_stat="def")
mv("brick_break","かわらわり","fighting","physical",75,100,15,0,"N","c p m",effect="brick_break")
mv("low_kick","けたぐり","fighting","physical",0,100,20,0,"N","c p m",base_power_callback="weight")
mv("vacuum_wave","しんくうは","fighting","special",40,100,30,1,"N","p m")
mv("bulk_up","ビルドアップ","fighting","status",0,T,20,0,"S","",**boosts(atk=1,**{"def":1}))
mv("secret_sword","しんぴのつるぎ","fighting","special",85,100,10,0,"N","p m sl",override_defensive_stat="def")
mv("cross_chop","クロスチョップ","fighting","physical",100,80,5,0,"N","c p m",crit_ratio=2)
mv("high_jump_kick","とびひざげり","fighting","physical",130,90,10,0,"N","c p m",effect="high_jump_kick")
mv("reversal","きしかいせい","fighting","physical",0,100,15,0,"N","c p m",base_power_callback="low_hp")
mv("counter","カウンター","fighting","physical",0,100,20,-5,"SC","c p",damage_callback="counter",effect="counter")
mv("detect","みきり","fighting","status",0,T,5,4,"S","",volatile_status="protect",effect="protect",stalling=True)
mv("quick_guard","ファストガード","fighting","status",0,T,15,3,"AS","",side_condition="quick_guard")
mv("final_gambit","いのちがけ","fighting","special",0,100,5,0,"N","p",damage_callback="final_gambit",effect="final_gambit")
mv("thunderous_kick","らいめいげり","fighting","physical",90,100,10,0,"N","c p m",**sec(100,boosts={"def":-1}))
mv("storm_throw","やまあらし","fighting","physical",60,100,10,0,"N","c p m",will_crit=True)
mv("karate_chop","からてチョップ","fighting","physical",50,100,25,0,"N","c p m",crit_ratio=2)
mv("rock_smash","いわくだき","fighting","physical",40,100,15,0,"N","c p m",**sec(50,boosts={"def":-1}))
mv("power_up_punch","グロウパンチ","fighting","physical",40,100,20,0,"N","c p m pu",**sec(100,self={"boosts":{"atk":1}}))
mv("low_sweep","ローキック","fighting","physical",65,100,20,0,"N","c p m",**sec(100,boosts={"spe":-1}))
mv("circle_throw","ともえなげ","fighting","physical",60,90,10,-6,"N","c p m",force_switch=True)
mv("hammer_arm","アームハンマー","fighting","physical",100,90,10,0,"N","c p m pu",**selfb(spe=-1))
mv("sky_uppercut","スカイアッパー","fighting","physical",85,90,15,0,"N","c p m pu",hits_invulnerable=["fly"])
mv("force_palm","はっけい","fighting","physical",60,100,10,0,"N","c p m",**sec(30,status="par"))
mv("seismic_toss","ちきゅうなげ","fighting","physical",0,100,20,0,"N","c p m",damage_callback="level")
mv("vital_throw","あてみなげ","fighting","physical",70,T,10,-1,"N","c p m")
mv("arm_thrust","つっぱり","fighting","physical",15,100,20,0,"N","c p m",multihit=[2,5])
mv("double_kick","にどげり","fighting","physical",30,100,30,0,"N","c p m",multihit=2)
mv("dynamic_punch","ばくれつパンチ","fighting","physical",100,50,5,0,"N","c p m pu",**sec(100,volatile_status="confusion"))
mv("revenge","リベンジ","fighting","physical",60,100,10,-4,"N","c p m",base_power_callback="avalanche")
# ---------------- GROUND ----------------
mv("earthquake","じしん","ground","physical",100,100,10,0,"A","p m",double_vs_invulnerable=["dig"])
mv("earth_power","だいちのちから","ground","special",90,100,10,0,"N","p m",**sec(10,boosts={"spd":-1}))
mv("high_horsepower","10まんばりき","ground","physical",95,95,10,0,"N","c p m")
mv("stomping_tantrum","じだんだ","ground","physical",75,100,10,0,"N","c p m",effect="stomping_tantrum",base_power_callback="stomping_tantrum")
mv("bulldoze","じならし","ground","physical",60,100,20,0,"A","p m",**sec(100,boosts={"spe":-1}))
mv("drill_run","ドリルライナー","ground","physical",80,95,10,0,"N","c p m",crit_ratio=2)
mv("sand_tomb","すなじごく","ground","physical",35,85,15,0,"N","p m",volatile_status="partially_trapped")
mv("spikes","まきびし","ground","status",0,T,20,0,"FS","rf",side_condition="spikes")
mv("mud_shot","マッドショット","ground","special",55,95,15,0,"N","p m",**sec(100,boosts={"spe":-1}))
mv("mud_slap","どろかけ","ground","special",20,100,10,0,"N","p m",**sec(100,boosts={"accuracy":-1}))
mv("dig","あなをほる","ground","physical",80,100,10,0,"N","c p m ch",effect="charge_move",semi_invulnerable="dig",no_sleep_talk=True)
mv("bone_rush","ボーンラッシュ","ground","physical",25,90,10,0,"N","p m",multihit=[2,5])
mv("headlong_rush","ぶちかまし","ground","physical",120,100,5,0,"N","c p m pu",**selfb(**{"def":-1,"spd":-1}))
mv("shore_up","すなあつめ","ground","status",0,T,5,0,"S","h",effect="shore_up")
mv("mud_bomb","どろばくだん","ground","special",65,85,10,0,"N","p m bu",**sec(30,boosts={"accuracy":-1}))
mv("sandstorm","すなあらし","rock","status",0,T,10,0,"ALL","w",weather="sand")
# ---------------- FLYING ----------------
mv("brave_bird","ブレイブバード","flying","physical",120,100,15,0,"N","c p m",recoil=[33,100])
mv("hurricane","ぼうふう","flying","special",110,70,10,0,"N","p m w",always_hit_in=["rain"],accuracy_in={"sun":50},hits_invulnerable=["fly"],**sec(30,volatile_status="confusion"))
mv("air_slash","エアスラッシュ","flying","special",75,95,15,0,"N","p m sl",**sec(30,volatile_status="flinch"))
mv("air_cutter","エアカッター","flying","special",60,95,25,0,"F","p m sl w",crit_ratio=2)
mv("acrobatics","アクロバット","flying","physical",55,100,15,0,"N","c p m",base_power_callback="acrobatics")
mv("aerial_ace","つばめがえし","flying","physical",60,T,20,0,"N","c p m sl")
mv("dual_wingbeat","ダブルウイング","flying","physical",40,90,10,0,"N","c p m",multihit=2)
mv("roost","はねやすめ","flying","status",0,T,5,0,"S","h",heal=[1,2],volatile_status="roost")
mv("tailwind","おいかぜ","flying","status",0,T,15,0,"AS","w",side_condition="tailwind")
mv("defog","きりばらい","flying","status",0,T,15,0,"N","p m rf bs",effect="defog",**boosts(evasion=-1))
mv("fly","そらをとぶ","flying","physical",90,95,15,0,"N","c p m ch",effect="charge_move",semi_invulnerable="fly",no_sleep_talk=True)
mv("drill_peck","ドリルくちばし","flying","physical",80,100,20,0,"N","c p m")
mv("feather_dance","フェザーダンス","flying","status",0,100,15,0,"N","p m rf da",**boosts(atk=-2))
mv("gust","かぜおこし","flying","special",40,100,35,0,"N","p m w",hits_invulnerable=["fly"],double_vs_invulnerable=["fly"])
mv("wing_attack","つばさでうつ","flying","physical",60,100,35,0,"N","c p m")
mv("peck","つつく","flying","physical",35,100,35,0,"N","c p m")
# ---------------- ROCK ----------------
mv("stone_edge","ストーンエッジ","rock","physical",100,80,5,0,"N","p m",crit_ratio=2)
mv("rock_slide","いわなだれ","rock","physical",75,90,10,0,"F","p m",**sec(30,volatile_status="flinch"))
mv("rock_blast","ロックブラスト","rock","physical",25,90,10,0,"N","p m bu",multihit=[2,5])
mv("head_smash","もろはのずつき","rock","physical",150,80,5,0,"N","c p m",recoil=[1,2])
mv("power_gem","パワージェム","rock","special",80,100,20,0,"N","p m")
mv("ancient_power","げんしのちから","rock","special",60,100,5,0,"N","p m",**sec(10,self={"boosts":{"atk":1,"def":1,"spa":1,"spd":1,"spe":1}}))
mv("stealth_rock","ステルスロック","rock","status",0,T,20,0,"FS","rf",side_condition="stealth_rock")
mv("rock_tomb","がんせきふうじ","rock","physical",60,95,15,0,"N","p m",**sec(100,boosts={"spe":-1}))
mv("accelerock","アクセルロック","rock","physical",40,100,20,1,"N","c p m")
mv("stone_axe","がんせきアックス","rock","physical",65,90,15,0,"N","c p m sl",effect="stone_axe")
mv("rock_polish","ロックカット","rock","status",0,T,20,0,"S","",**boosts(spe=2))
mv("wide_guard","ワイドガード","rock","status",0,T,10,3,"AS","",side_condition="wide_guard")
mv("smack_down","うちおとす","rock","physical",50,100,15,0,"N","p m",volatile_status="smack_down",hits_invulnerable=["fly"])
mv("rock_throw","いわおとし","rock","physical",50,90,15,0,"N","p m")
mv("salt_cure","しおづけ","rock","physical",40,100,15,0,"N","p m",volatile_status="salt_cure")
mv("meteor_beam","メテオビーム","rock","special",120,90,10,0,"N","p m ch",effect="meteor_beam",no_sleep_talk=True)
# ---------------- STEEL ----------------
mv("iron_head","アイアンヘッド","steel","physical",80,100,15,0,"N","c p m",**sec(30,volatile_status="flinch"))
mv("flash_cannon","ラスターカノン","steel","special",80,100,10,0,"N","p m",**sec(10,boosts={"spd":-1}))
mv("steel_beam","てっていこうせん","steel","special",140,95,5,0,"N","p m",effect="steel_beam")
mv("heavy_slam","ヘビーボンバー","steel","physical",0,100,10,0,"N","c p m cm",base_power_callback="heavy_slam")
mv("smart_strike","スマートホーン","steel","physical",70,T,10,0,"N","c p m")
mv("meteor_mash","コメットパンチ","steel","physical",90,90,10,0,"N","c p m pu",**sec(20,self={"boosts":{"atk":1}}))
mv("bullet_punch","バレットパンチ","steel","physical",40,100,30,1,"N","c p m pu")
mv("iron_defense","てっぺき","steel","status",0,T,15,0,"S","",**boosts(**{"def":2}))
mv("steel_wing","はがねのつばさ","steel","physical",70,90,25,0,"N","c p m",**sec(10,self={"boosts":{"def":1}}))
mv("metal_claw","メタルクロー","steel","physical",50,95,35,0,"N","c p m",**sec(10,self={"boosts":{"atk":1}}))
mv("gyro_ball","ジャイロボール","steel","physical",0,100,5,0,"N","c p m bu",base_power_callback="gyro_ball")
mv("anchor_shot","アンカーショット","steel","physical",80,100,20,0,"N","c p m",**sec(100,volatile_status="trapped"))
mv("iron_tail","アイアンテール","steel","physical",100,75,15,0,"N","c p m",**sec(30,boosts={"def":-1}))
mv("metal_sound","きんぞくおん","steel","status",0,85,40,0,"N","p m s rf bs",**boosts(spd=-2))
mv("gear_grind","ギアソーサー","steel","physical",50,85,15,0,"N","c p m",multihit=2)
# ---------------- BUG ----------------
mv("u_turn","とんぼがえり","bug","physical",70,100,20,0,"N","c p m",self_switch=True)
mv("bug_buzz","むしのさざめき","bug","special",90,100,10,0,"N","p m s bs",**sec(10,boosts={"spd":-1}))
mv("leech_life","きゅうけつ","bug","physical",80,100,10,0,"N","c p m h",drain=[1,2])
mv("x_scissor","シザークロス","bug","physical",80,100,15,0,"N","c p m sl")
mv("megahorn","メガホーン","bug","physical",120,85,10,0,"N","c p m")
mv("first_impression","であいがしら","bug","physical",90,100,10,2,"N","c p m",effect="fake_out")
mv("quiver_dance","ちょうのまい","bug","status",0,T,20,0,"S","da",**boosts(spa=1,spd=1,spe=1))
mv("struggle_bug","むしのていこう","bug","special",50,100,20,0,"F","p m",**sec(100,boosts={"spa":-1}))
mv("lunge","とびかかる","bug","physical",80,100,15,0,"N","c p m",**sec(100,boosts={"atk":-1}))
mv("sticky_web","ねばねばネット","bug","status",0,T,20,0,"FS","rf",side_condition="sticky_web")
mv("infestation","まとわりつく","bug","special",20,100,20,0,"N","c p m",volatile_status="partially_trapped")
mv("pin_missile","ミサイルばり","bug","physical",25,95,20,0,"N","p m",multihit=[2,5])
mv("string_shot","いとをはく","bug","status",0,95,40,0,"F","p m rf",**boosts(spe=-2))
mv("rage_powder","いかりのこな","bug","status",0,T,20,2,"S","pw",volatile_status="rage_powder")
mv("fury_cutter","れんぞくぎり","bug","physical",40,95,20,0,"N","c p m sl",effect="fury_cutter",base_power_callback="fury_cutter")
mv("skitter_smack","はいよるいちげき","bug","physical",70,90,10,0,"N","c p m",**sec(100,boosts={"spa":-1}))
mv("pounce","とびつく","bug","physical",50,100,20,0,"N","c p m",**sec(100,boosts={"spe":-1}))
mv("bug_bite","むしくい","bug","physical",60,100,20,0,"N","c p m")
# ---------------- POISON ----------------
mv("sludge_bomb","ヘドロばくだん","poison","special",90,100,10,0,"N","p m bu",**sec(30,status="psn"))
mv("sludge_wave","ヘドロウェーブ","poison","special",95,100,10,0,"A","p m",**sec(10,status="psn"))
mv("gunk_shot","ダストシュート","poison","physical",120,80,5,0,"N","p m",**sec(30,status="psn"))
mv("poison_jab","どくづき","poison","physical",80,100,20,0,"N","c p m",**sec(30,status="psn"))
mv("toxic","どくどく","poison","status",0,90,10,0,"N","p m rf",status="tox",effect="toxic")
mv("toxic_spikes","どくびし","poison","status",0,T,20,0,"FS","rf",side_condition="toxic_spikes")
mv("venoshock","ベノムショック","poison","special",65,100,10,0,"N","p m",base_power_callback="venoshock")
mv("clear_smog","クリアスモッグ","poison","special",50,T,15,0,"N","p m",effect="clear_smog")
mv("cross_poison","クロスポイズン","poison","physical",70,100,20,0,"N","c p m sl",crit_ratio=2,**sec(10,status="psn"))
mv("acid_spray","アシッドボム","poison","special",40,100,20,0,"N","p m bu",**sec(100,boosts={"spd":-2}))
mv("poison_fang","どくどくのキバ","poison","physical",50,100,15,0,"N","c p m bi",**sec(50,status="tox"))
mv("baneful_bunker","トーチカ","poison","status",0,T,10,4,"S","",volatile_status="baneful_bunker",effect="protect",stalling=True)
mv("coil","とぐろをまく","poison","status",0,T,20,0,"S","",**boosts(atk=1,accuracy=1,**{"def":1}))
mv("sludge","ヘドロこうげき","poison","special",65,100,20,0,"N","p m",**sec(30,status="psn"))
mv("acid_armor","とける","poison","status",0,T,20,0,"S","",**boosts(**{"def":2}))
mv("poison_tail","ポイズンテール","poison","physical",50,100,25,0,"N","c p m",crit_ratio=2,**sec(10,status="psn"))
mv("poison_gas","どくガス","poison","status",0,90,40,0,"F","p m rf",status="psn")
# ---------------- PSYCHIC ----------------
mv("psychic","サイコキネシス","psychic","special",90,100,10,0,"N","p m",**sec(10,boosts={"spd":-1}))
mv("psyshock","サイコショック","psychic","special",80,100,10,0,"N","p m",override_defensive_stat="def")
mv("psycho_cut","サイコカッター","psychic","physical",70,100,20,0,"N","p m sl",crit_ratio=2)
mv("calm_mind","めいそう","psychic","status",0,T,20,0,"S","",**boosts(spa=1,spd=1))
mv("expanding_force","ワイドフォース","psychic","special",80,100,10,0,"N","p m",effect="expanding_force")
mv("stored_power","アシストパワー","psychic","special",20,100,10,0,"N","p m",base_power_callback="stored_power")
mv("future_sight","みらいよち","psychic","special",120,100,10,0,"N","",effect="future_sight")
mv("trick_room","トリックルーム","psychic","status",0,T,5,-7,"ALL","",pseudo_weather="trick_room")
mv("psychic_terrain","サイコフィールド","psychic","status",0,T,10,0,"ALL","",terrain="psychic")
mv("teleport","テレポート","psychic","status",0,T,20,-6,"S","",self_switch=True,effect="teleport")
mv("zen_headbutt","しねんのずつき","psychic","physical",80,90,15,0,"N","c p m",**sec(20,volatile_status="flinch"))
mv("psychic_fangs","サイコファング","psychic","physical",85,100,10,0,"N","c p m bi",effect="brick_break")
mv("trick","トリック","psychic","status",0,100,10,0,"N","p m",effect="trick")
mv("agility","こうそくいどう","psychic","status",0,T,30,0,"S","",**boosts(spe=2))
mv("amnesia","ドわすれ","psychic","status",0,T,20,0,"S","",**boosts(spd=2))
mv("cosmic_power","コスモパワー","psychic","status",0,T,20,0,"S","",**boosts(spd=1,**{"def":1}))
mv("light_screen","ひかりのかべ","psychic","status",0,T,30,0,"AS","",side_condition="light_screen")
mv("reflect","リフレクター","psychic","status",0,T,20,0,"AS","",side_condition="reflect")
mv("heal_pulse","いやしのはどう","psychic","status",0,T,10,0,"N","p pl rf h bs",effect="heal_pulse")
mv("psyblade","サイコブレイド","psychic","physical",80,100,15,0,"N","c p m sl",effect="psyblade")
mv("extrasensory","じんつうりき","psychic","special",80,100,20,0,"N","p m",**sec(10,volatile_status="flinch"))
mv("dream_eater","ゆめくい","psychic","special",100,100,15,0,"N","p m h",drain=[1,2],effect="dream_eater")
mv("hypnosis","さいみんじゅつ","psychic","status",0,60,20,0,"N","p m rf",status="slp")
mv("meditate","ヨガのポーズ","psychic","status",0,T,40,0,"S","",**boosts(atk=1))
mv("gravity","じゅうりょく","psychic","status",0,T,5,0,"ALL","",pseudo_weather="gravity")
mv("confusion","ねんりき","psychic","special",50,100,25,0,"N","p m",**sec(10,volatile_status="confusion"))
mv("psybeam","サイケこうせん","psychic","special",65,100,20,0,"N","p m",**sec(10,volatile_status="confusion"))
# ---------------- DRAGON ----------------
mv("draco_meteor","りゅうせいぐん","dragon","special",130,90,5,0,"N","p m",**selfb(spa=-2))
mv("dragon_pulse","りゅうのはどう","dragon","special",85,100,10,0,"N","p m pl")
mv("dragon_claw","ドラゴンクロー","dragon","physical",80,100,15,0,"N","c p m")
mv("outrage","げきりん","dragon","physical",120,100,10,0,"RN","c p m",locked_move=True)
mv("dragon_dance","りゅうのまい","dragon","status",0,T,20,0,"S","da",**boosts(atk=1,spe=1))
mv("dragon_tail","ドラゴンテール","dragon","physical",60,90,10,-6,"N","c p m",force_switch=True)
mv("breaking_swipe","ドラゴンアロー","dragon","physical",60,100,15,0,"F","c p m",**sec(100,boosts={"atk":-1}))
mv("scale_shot","スケイルショット","dragon","physical",25,90,20,0,"N","p m",multihit=[2,5],**selfb(spe=1,**{"def":-1}))
mv("dragon_rush","ドラゴンダイブ","dragon","physical",100,75,10,0,"N","c p m cm",**sec(20,volatile_status="flinch"))
mv("dragon_breath","りゅうのいぶき","dragon","special",60,100,20,0,"N","p m",**sec(30,status="par"))
mv("dual_chop","ダブルチョップ","dragon","physical",40,90,15,0,"N","c p m",multihit=2)
mv("dragon_hammer","ドラゴンハンマー","dragon","physical",90,100,15,0,"N","c p m")
mv("twister","たつまき","dragon","special",40,100,20,0,"F","p m w",hits_invulnerable=["fly"],double_vs_invulnerable=["fly"],**sec(20,volatile_status="flinch"))
# ---------------- DARK ----------------
mv("knock_off","はたきおとす","dark","physical",65,100,20,0,"N","c p m",effect="knock_off",base_power_callback="knock_off")
mv("crunch","かみくだく","dark","physical",80,100,15,0,"N","c p m bi",**sec(20,boosts={"def":-1}))
mv("dark_pulse","あくのはどう","dark","special",80,100,15,0,"N","p m pl",**sec(20,volatile_status="flinch"))
mv("sucker_punch","ふいうち","dark","physical",70,100,5,1,"N","c p m",effect="sucker_punch")
mv("foul_play","イカサマ","dark","physical",95,100,15,0,"N","c p m",use_target_offense=True)
mv("night_slash","つじぎり","dark","physical",70,100,15,0,"N","c p m sl",crit_ratio=2)
mv("taunt","ちょうはつ","dark","status",0,100,20,0,"N","p m rf bs",volatile_status="taunt")
mv("parting_shot","すてゼリフ","dark","status",0,100,20,0,"N","p m s rf bs",self_switch=True,**boosts(atk=-1,spa=-1))
mv("nasty_plot","わるだくみ","dark","status",0,T,20,0,"S","",**boosts(spa=2))
mv("throat_chop","じごくづき","dark","physical",80,100,15,0,"N","c p m",volatile_status="throat_chop")
mv("snarl","バークアウト","dark","special",55,95,15,0,"F","p m s bs",**sec(100,boosts={"spa":-1}))
mv("kowtow_cleave","ドゲザン","dark","physical",85,T,10,0,"N","c p m sl")
mv("ceaseless_edge","ひけん・ちえなみ","dark","physical",65,90,15,0,"N","c p m sl",effect="ceaseless_edge")
mv("bite","かみつく","dark","physical",60,100,25,0,"N","c p m bi",**sec(30,volatile_status="flinch"))
mv("assurance","ダメおし","dark","physical",60,100,10,0,"N","c p m",effect="assurance",base_power_callback="assurance")
mv("payback","しっぺがえし","dark","physical",50,100,10,0,"N","c p m",base_power_callback="payback")
mv("fake_tears","うそなき","dark","status",0,100,20,0,"N","p m rf",**boosts(spd=-2))
mv("hone_claws","つめとぎ","dark","status",0,T,15,0,"S","",**boosts(atk=1,accuracy=1))
mv("memento","おきみやげ","dark","status",0,100,10,0,"N","p m rf",self_destruct="if_hit",**boosts(atk=-2,spa=-2))
mv("switcheroo","すりかえ","dark","status",0,100,10,0,"N","p m",effect="trick")
mv("darkest_lariat","DDラリアット","dark","physical",85,100,10,0,"N","c p m",ignore_defensive=True,ignore_evasion=True)
mv("false_surrender","どげざつき","dark","physical",80,T,10,0,"N","c p m")
mv("power_trip","つけあがる","dark","physical",20,100,10,0,"N","c p m",base_power_callback="stored_power")
mv("brutal_swing","ぶんまわす","dark","physical",60,100,20,0,"A","c p m")
mv("thief","どろぼう","dark","physical",60,100,25,0,"N","c p m")
mv("punishment","おしおき","dark","physical",0,100,5,0,"N","c p m",base_power_callback="punishment")
mv("night_daze","ナイトバースト","dark","special",85,95,10,0,"N","p m",**sec(40,boosts={"accuracy":-1}))
# ---------------- GHOST ----------------
mv("shadow_ball","シャドーボール","ghost","special",80,100,15,0,"N","p m bu",**sec(20,boosts={"spd":-1}))
mv("shadow_claw","シャドークロー","ghost","physical",70,100,15,0,"N","c p m",crit_ratio=2)
mv("shadow_sneak","かげうち","ghost","physical",40,100,30,1,"N","c p m")
mv("hex","たたりめ","ghost","special",65,100,10,0,"N","p m",base_power_callback="hex")
mv("phantom_force","ゴーストダイブ","ghost","physical",90,100,10,0,"N","c m ch",effect="charge_move",semi_invulnerable="phantom_force",breaks_protect=True,no_sleep_talk=True)
mv("poltergeist","ポルターガイスト","ghost","physical",110,90,5,0,"N","p m",effect="poltergeist")
mv("curse","のろい","ghost","status",0,T,10,0,"N","bs",effect="curse")
mv("destiny_bond","みちづれ","ghost","status",0,T,5,0,"S","",volatile_status="destiny_bond",no_encore=True)
mv("shadow_punch","シャドーパンチ","ghost","physical",60,T,20,0,"N","c p m pu")
mv("night_shade","ナイトヘッド","ghost","special",0,100,15,0,"N","p m",damage_callback="level")
mv("astonish","おどろかす","ghost","physical",30,100,15,0,"N","c p m",**sec(30,volatile_status="flinch"))
mv("bitter_malice","うらみつらみ","ghost","special",75,100,10,0,"N","p m",**sec(100,boosts={"atk":-1}))
mv("lick","したでなめる","ghost","physical",30,100,30,0,"N","c p m",**sec(30,status="par"))
mv("confuse_ray","あやしいひかり","ghost","status",0,100,10,0,"N","p m rf",volatile_status="confusion")
mv("spirit_shackle","かげぬい","ghost","physical",80,100,10,0,"N","p m",**sec(100,volatile_status="trapped"))
mv("nightmare","あくむ","ghost","status",0,100,15,0,"N","p m",volatile_status="nightmare")
mv("shadow_bone","シャドーボーン","ghost","physical",85,100,10,0,"N","p m",**sec(20,boosts={"def":-1}))
mv("ominous_wind","あやしいかぜ","ghost","special",60,100,5,0,"N","p m w",**sec(10,self={"boosts":{"atk":1,"def":1,"spa":1,"spd":1,"spe":1}}))
# ---------------- FAIRY ----------------
mv("moonblast","ムーンフォース","fairy","special",95,100,15,0,"N","p m",**sec(30,boosts={"spa":-1}))
mv("dazzling_gleam","マジカルシャイン","fairy","special",80,100,10,0,"F","p m")
mv("play_rough","じゃれつく","fairy","physical",90,90,10,0,"N","c p m",**sec(10,boosts={"atk":-1}))
mv("draining_kiss","ドレインキッス","fairy","special",50,100,10,0,"N","c p m h",drain=[3,4])
mv("spirit_break","ソウルクラッシュ","fairy","physical",75,100,15,0,"N","c p m",**sec(100,boosts={"spa":-1}))
mv("misty_terrain","ミストフィールド","fairy","status",0,T,10,0,"ALL","",terrain="misty")
mv("misty_explosion","ミストバースト","fairy","special",100,100,5,0,"A","p m",self_destruct="always",effect="misty_explosion")
mv("charm","あまえる","fairy","status",0,100,20,0,"N","p m rf",**boosts(atk=-2))
mv("baby_doll_eyes","つぶらなひとみ","fairy","status",0,100,30,1,"N","p m rf",**boosts(atk=-1))
mv("sweet_kiss","てんしのキッス","fairy","status",0,75,10,0,"N","p m rf",volatile_status="confusion")
mv("fairy_wind","ようせいのかぜ","fairy","special",40,100,30,0,"N","p m w")
mv("disarming_voice","チャームボイス","fairy","special",40,T,15,0,"F","p m s bs")
mv("moonlight","つきのひかり","fairy","status",0,T,5,0,"S","h",effect="weather_heal")
mv("natures_madness","しぜんのいかり","fairy","special",0,90,10,0,"N","p m",damage_callback="half_hp")

out = {}
loc = {}
for (id, ja, type, cat, power, acc, pp, prio, tgt, flags, extra) in M:
    d = {"type": type, "category": cat, "power": power, "accuracy": acc, "pp": pp, "priority": prio,
         "target": TGT[tgt], "flags": [FLAG[f] for f in flags.split() if f]}
    d.update(extra)
    assert id not in out, id
    out[id] = d
    loc[id] = ja
os.makedirs("data/moves", exist_ok=True)
json.dump(out, open("data/moves/moves.json", "w"), ensure_ascii=False, indent=1)
os.makedirs("data/localization", exist_ok=True)
lp = "data/localization/ja.json"
L = json.load(open(lp)) if os.path.exists(lp) else {}
L["moves"] = loc
json.dump(L, open(lp, "w"), ensure_ascii=False, indent=1)
print("moves:", len(out))
