#!/usr/bin/env python3
"""Recommended competitive sets per species -> data/sets/sets.json (validated against learnsets)."""
import json, glob, os
moves = json.load(open("data/moves/moves.json"))
species = {}
for f in glob.glob("data/species/*.json"):
    species.update(json.load(open(f)))
def learnable(sid):
    sp = species[sid]; out=set()
    for e in sp["learnset"]["level"]: out.add(e["move"])
    out.update(sp["learnset"]["tm"])
    if sp.get("evolves_from"): out |= learnable(sp["evolves_from"])
    return out
S = {}
def st(sid, name, mv, item, nature, evs, ability=None, role="attacker"):
    L = learnable(sid)
    for m in mv: assert m in L, (sid, name, m)
    S.setdefault(sid, []).append({"name": name, "moves": mv, "item": item, "nature": nature, "evs": evs,
                                  "ability": ability or species[sid]["abilities"]["0"], "role": role})
HA = {"hp":252,"atk":252,"spe":4}; HD = {"hp":252,"def":252,"spd":4}; HSD = {"hp":252,"spd":252,"def":4}
AS = {"atk":252,"spe":252,"hp":4}; CS = {"spa":252,"spe":252,"hp":4}; HC = {"hp":252,"spa":252,"spe":4}
st("renny","rest_talk",["waterfall","ice_punch","rest","sleep_talk"],"leftovers","adamant",HA,role="bulky_attacker")
st("renny","band",["liquidation","ice_punch","crunch","aqua_jet"],"choice_band","adamant",HA)
st("renny","yawn_pivot",["waterfall","yawn","rest","flip_turn"],"chesto_berry","impish",HD,role="support")
st("jinpachi","sd_lo",["flare_blitz","close_combat","swords_dance","extreme_speed"],"life_orb","jolly",AS,role="sweeper")
st("jinpachi","scarf",["flare_blitz","close_combat","u_turn","wild_charge"],"choice_scarf","jolly",AS)
st("jinpachi","band",["flare_blitz","close_combat","knock_off","u_turn"],"choice_band","adamant",AS)
st("hyu","specs",["shadow_ball","dark_pulse","thunderbolt","energy_ball"],"choice_specs","timid",CS)
st("hyu","nasty_plot",["shadow_ball","focus_blast","nasty_plot","substitute"],"life_orb","timid",CS,role="sweeper")
st("hyu","wisp_hex",["will_o_wisp","hex","pain_split","shadow_sneak"],"leftovers","timid",{"hp":252,"spe":252,"spa":4},role="support")
st("muni","minimize",["minimize","moonblast","wish","protect"],"leftovers","bold",HD,role="stall")
st("muni","screens",["reflect","light_screen","thunder_wave","moonblast"],"light_clay","bold",HD,role="support")
st("muni","support",["thunder_wave","encore","wish","moonblast"],"leftovers","calm",HSD,role="support")
st("gel","veil",["blizzard","freeze_dry","aurora_veil","moonblast"],"light_clay","timid",CS,role="weather")
st("gel","specs",["blizzard","freeze_dry","moonblast","thunderbolt"],"choice_specs","timid",CS,role="weather")
st("gel","calm_mind",["blizzard","calm_mind","freeze_dry","recover"],"leftovers","timid",{"hp":252,"spe":252,"spa":4},role="weather")
st("neo","eviolite_sd",["sacred_sword","night_slash","swords_dance","psycho_cut"],"eviolite","jolly",AS,role="sweeper")
st("neo","scarf",["sacred_sword","x_scissor","night_slash","aerial_ace"],"choice_scarf","jolly",AS)
st("neo","steadfast_sash",["sacred_sword","night_slash","swords_dance","aqua_cutter"],"focus_sash","jolly",AS,ability="steadfast",role="sweeper")
st("trans","sd_lo",["sacred_sword","stone_axe","swords_dance","psycho_cut"],"life_orb","adamant",AS,role="sweeper")
st("trans","band",["sacred_sword","high_horsepower","psycho_cut","x_scissor"],"choice_band","adamant",AS)
st("trans","rocks",["stealth_rock","sacred_sword","stone_axe","u_turn"],"leftovers","adamant",HA,role="support")
st("marutan","defog_wall",["roost","defog","air_slash","toxic"],"leftovers","bold",HD,role="wall")
st("marutan","cosmic",["cosmic_power","roost","stored_power","wish"],"leftovers","calm",HSD,role="stall")
st("marutan","support",["tailwind","heal_bell","roost","hurricane"],"leftovers","calm",HSD,role="support")
st("namazuo","sd_lo",["wild_charge","iron_head","swords_dance","night_slash"],"life_orb","jolly",AS,role="sweeper")
st("namazuo","scarf",["wild_charge","iron_head","volt_switch","knock_off"],"choice_scarf","jolly",AS)
st("namazuo","band",["wild_charge","iron_head","knock_off","x_scissor"],"choice_band","adamant",AS)
st("honebami","unburden_acro",["acrobatics","iron_head","swords_dance","night_slash"],"sitrus_berry","jolly",AS,role="sweeper")
st("honebami","sash_sd",["brave_bird","iron_head","swords_dance","kowtow_cleave"],"focus_sash","jolly",AS,role="sweeper")
st("honebami","band",["brave_bird","iron_head","kowtow_cleave","u_turn"],"choice_band","jolly",AS)
st("jinpachi_r","rocks_tank",["stealth_rock","stone_edge","earthquake","body_press"],"leftovers","impish",HD,role="wall")
st("jinpachi_r","sd_wp",["swords_dance","stone_edge","earthquake","heavy_slam"],"weakness_policy","adamant",HA,role="sweeper")
st("jinpachi_r","band",["head_smash","stone_edge","earthquake","fire_punch"],"choice_band","brave",HA)
st("hyu_r","lo",["leaf_storm","shadow_ball","giga_drain","sludge_bomb"],"life_orb","timid",CS,role="sweeper")
st("hyu_r","specs",["leaf_storm","sludge_bomb","shadow_ball","psychic"],"choice_specs","timid",CS)
st("hyu_r","sub_seed",["substitute","leech_seed","leaf_storm","giga_drain"],"leftovers","timid",{"hp":252,"spe":252,"spa":4},role="stall")
st("renny_r","band",["double_edge","extreme_speed","play_rough","earthquake"],"choice_band","adamant",HA)
st("renny_r","bulk_up",["bulk_up","body_slam","extreme_speed","earthquake"],"leftovers","adamant",HA,role="bulky_attacker")
st("renny_r","wish",["body_slam","wish","protect","extreme_speed"],"leftovers","impish",HD,role="support")
st("muni_r_dragon","dd",["dragon_dance","dragon_claw","roost","earthquake"],"leftovers","jolly",AS,role="sweeper")
st("muni_r_dragon","bulky",["dragon_tail","roost","haze","toxic"],"leftovers","impish",HD,role="wall")
st("muni_r_dragon","mixed",["draco_meteor","flamethrower","ice_beam","u_turn"],"choice_specs","timid",CS)
st("muni_r_bug","quiver",["quiver_dance","bug_buzz","sleep_powder","air_slash"],"leftovers","timid",CS,role="sweeper")
st("muni_r_bug","powder_sash",["sleep_powder","stun_spore","u_turn","sticky_web"],"focus_sash","timid",{"hp":252,"spe":252,"spa":4},role="support")
st("muni_r_bug","quiver_sub",["quiver_dance","bug_buzz","substitute","giga_drain"],"leftovers","timid",CS,role="sweeper")
st("muni_r_normal","minimize_bp",["minimize","baton_pass","substitute","body_slam"],"leftovers","impish",HD,role="support")
st("muni_r_normal","stall",["minimize","soft_boiled","body_slam","toxic"],"leftovers","impish",HD,role="stall")
st("muni_r_normal","support",["yawn","wish","encore","body_slam"],"leftovers","impish",HD,role="support")
st("gel_r_poison","wall",["toxic","recover","poison_jab","haze"],"black_sludge","impish",HD,role="wall")
st("gel_r_poison","tspikes",["toxic_spikes","recover","poison_jab","earthquake"],"black_sludge","impish",HD,role="wall")
st("gel_r_poison","coil",["coil","poison_jab","recover","earthquake"],"leftovers","careful",HSD,role="bulky_attacker")
st("gel_r_dark","pivot",["knock_off","parting_shot","recover","foul_play"],"leftovers","impish",HD,role="wall")
st("gel_r_dark","np",["nasty_plot","dark_pulse","recover","ice_beam"],"leftovers","bold",{"hp":252,"def":252,"spa":4},role="bulky_attacker")
st("gel_r_dark","taunt",["taunt","knock_off","recover","toxic"],"leftovers","careful",HSD,role="wall")
st("trans_r","sd_lo",["swords_dance","psycho_cut","sacred_sword","night_slash"],"life_orb","jolly",AS,role="sweeper")
st("trans_r","calm_mind",["calm_mind","psychic","aura_sphere","shadow_ball"],"leftovers","timid",CS,role="bulky_attacker")
st("trans_r","scarf",["psycho_cut","sacred_sword","x_scissor","trick"],"choice_scarf","jolly",AS)
os.makedirs("data/sets", exist_ok=True)
json.dump(S, open("data/sets/sets.json","w"), ensure_ascii=False, indent=1)
print("sets:", sum(len(v) for v in S.values()), "species:", len(S))
